### ISSUE TITLE
Is this compatible with firebase functions?

### ISSUE THREAD

**Issue by protoEvangelion** [benweier/connect-session-firebase#75]
@benweier Is it theoretically possible to wire up `connect-session-firebase` to **firebase cloud functions**?

**Comment by benweier** [comment]
It is theoretically possible. Connect Session Firebase wraps the standard `firebase-admin` package to read/write session data to the realtime database, so any `firebase-functions` feature that listens and responds to database events should operate completely independently. The obvious caveat is that Firebase Functions are still in beta and subject to change.

**Comment by protoEvangelion** [comment]
Got it, I just thought there may be limitations with accessing session storage after a firebase function spins down because it is not persistent like a server.

Some people's code I looked at seems like they are still able to have sessions with functions, but I am not sure how to work that out with this package.

This answer says if I store things under the key: `__session` it will work.

Do you think that would be compatible?

**Comment by benweier** [comment]
You can definitely use `__session` as your cookie key which would look like this:

```
app.use(session({
  store: new FirebaseStore({
    database: ref.database()
  }),
  key: '__session',
  secret: 'keyboard cat',
  resave: true,
  saveUninitialized: true,
}));
```

**Comment by Youdaman** [comment]
FirebaseStore works fine in a standard Node environment but I cannot get it to work with in the Firebase cloud functions environment.

I'm using it in an oauth scenario where I'm setting/getting tokens, but rather than re-use the same session record for the exchange, it creates a new entry in the database for each leg.

I tried using both `key` and `name` set to `__session` however it didn't make a difference.

Like I said it works fine in normal Node, but not when using Firebase functions setup, as it seems each connection is a blank slate and the session gets created anew for each request.

If there's any magic trick to getting it to work I'd love to know :)
